import { computed, reactive, ref } from "vue"
import { createEmployeeType, updateEmployeeType } from "../api/employeeType.api.js"
function emptyForm() { return { companyId: "", branchId: "", code: "", name: "", structureMode: "DIRECT", dashboardCategory: "", positionAssignmentMode: "SPECIFIC_POSITIONS", positionIds: [], children: [], description: "", status: "ACTIVE" } }
function normalizeCode(value) { return String(value || "").trim().replace(/\s+/g, "_").toUpperCase().replace(/[^A-Z0-9_-]/g, "") }
export function useEmployeeTypeForm() {
 const form=reactive(emptyForm()), errors=reactive({}), saving=ref(false), mode=ref("create"), employeeTypeId=ref(null); const isEdit=computed(()=>mode.value==="edit")
 function reset(){Object.assign(form,emptyForm());Object.keys(errors).forEach(k=>delete errors[k]);employeeTypeId.value=null}
 function openCreate(){reset();mode.value="create"}
 function openEdit(row){reset();mode.value="edit";employeeTypeId.value=row.id;Object.assign(form,{companyId:row.companyId||row.company?.id||"",branchId:row.branchId||row.branch?.id||"",code:row.code||"",name:row.name||"",structureMode:row.children?.length?"CHILD":"DIRECT",dashboardCategory:row.dashboardCategory||"",positionAssignmentMode:row.positionAssignmentMode||"SPECIFIC_POSITIONS",positionIds:(row.positionIds||[]).map(x=>x.id||x._id||x),children:(row.children||[]).map(c=>({id:c.id,code:c.code||"",name:c.name||"",dashboardCategory:c.dashboardCategory||"",positionAssignmentMode:c.positionAssignmentMode||"SPECIFIC_POSITIONS",positionIds:(c.positionIds||[]).map(x=>x.id||x._id||x)})),description:row.description||"",status:row.status==="ARCHIVED"?"INACTIVE":row.status||"ACTIVE"})}
 function addChild(){form.structureMode="CHILD";form.positionIds=[];form.children.push({code:"",name:"",dashboardCategory:"",positionAssignmentMode:"SPECIFIC_POSITIONS",positionIds:[]})}
 function removeChild(i){form.children.splice(i,1)} function clearError(f){delete errors[f]}
 function buildPayload(){return {companyId:form.companyId,branchId:form.branchId,code:normalizeCode(form.code),name:form.name.trim(),dashboardCategory:normalizeCode(form.dashboardCategory),positionAssignmentMode:form.structureMode==="DIRECT"?form.positionAssignmentMode:"SPECIFIC_POSITIONS",positionIds:form.structureMode==="DIRECT"&&form.positionAssignmentMode==="SPECIFIC_POSITIONS"?[...form.positionIds]:[],children:form.structureMode==="CHILD"?form.children.map(c=>({code:normalizeCode(c.code||c.name),name:c.name.trim(),dashboardCategory:normalizeCode(c.dashboardCategory),positionAssignmentMode:c.positionAssignmentMode,positionIds:c.positionAssignmentMode==="SPECIFIC_POSITIONS"?[...c.positionIds]:[]})):[],description:form.description.trim(),status:form.status}}
 async function save(){saving.value=true;Object.keys(errors).forEach(k=>delete errors[k]);try{const payload=buildPayload();return isEdit.value?await updateEmployeeType(employeeTypeId.value,payload):await createEmployeeType(payload)}catch(e){Object.assign(errors,e?.response?.data?.error?.fields||{});throw e}finally{saving.value=false}}
 return {form,errors,saving,mode,employeeTypeId,isEdit,openCreate,openEdit,addChild,removeChild,clearError,save}
}
