export function createPositionColumns(t) {
    return [
        {
            field: "code",
            header: t("organization.position.code"),
            sortable: true,
            frozen: true,
            alignFrozen: "left",
            width: "9rem",
            minWidth: "9rem",
            maxWidth: "9rem",
            headerClass: "enterprise-table__code-header",
            bodyClass: "enterprise-table__code-cell",
        },
        {
            field: "title",
            header: t("organization.position.name"),
            sortable: true,
            width: "14rem",
            minWidth: "14rem",
        },
        {
            field: "company",
            header: t("organization.position.company"),
            sortable: false,
            width: "13rem",
            minWidth: "13rem",
        },
        {
            field: "branch",
            header: t("organization.position.branch"),
            sortable: false,
            width: "13rem",
            minWidth: "13rem",
        },
        {
            field: "department",
            header: t("organization.position.department"),
            sortable: false,
            width: "13rem",
            minWidth: "13rem",
        },
        {
            field: "reportsToPosition",
            header: t("organization.position.reportsTo"),
            sortable: false,
            width: "14rem",
            minWidth: "14rem",
        },
        {
            field: "level",
            header: t("organization.position.level"),
            sortable: true,
            width: "7rem",
            minWidth: "7rem",
        },
        {
            field: "isManager",
            header: t("organization.position.managerPosition"),
            sortable: false,
            width: "8rem",
            minWidth: "8rem",
        },
        {
            field: "status",
            header: t("common.status"),
            sortable: true,
            width: "8rem",
            minWidth: "8rem",
        },
        {
            field: "updatedAt",
            header: t("common.updatedAt"),
            sortable: true,
            width: "11rem",
            minWidth: "11rem",
        },
    ]
}
