<script setup>
import Drawer from "primevue/drawer"
import ProgressSpinner from "primevue/progressspinner"
import Tag from "primevue/tag"
defineProps({visible:Boolean,employee:{type:Object,default:null},loading:Boolean})
defineEmits(['update:visible','edit'])
const value=(item)=>item??'—'
const org=(item)=>item?.displayName||item?.title||item?.name||item?.code||'—'
const address=(item)=>[item?.detail,item?.village?.name,item?.commune?.name,item?.district?.name,item?.province?.name,item?.country?.name].filter(Boolean).join(', ')||'—'
</script>
<template><Drawer :visible="visible" position="right" class="employee-details-drawer" header="Employee Details" @update:visible="$emit('update:visible',$event)">
  <div v-if="loading" class="employee-details__loading"><ProgressSpinner/></div>
  <div v-else-if="employee" class="employee-details">
    <header class="employee-details__profile"><img v-if="employee.profileImageUrl" :src="employee.profileImageUrl" alt=""/><div><h2>{{ employee.displayName || employee.employeeCode }}</h2><p>{{ employee.employeeCode }}</p><Tag :value="employee.employmentStatus" :severity="employee.employmentStatus==='WORKING'?'success':'warn'"/></div></header>
    <section><h3>Basic Information</h3><dl><div><dt>Khmer Name</dt><dd>{{ value([employee.khmerFirstName,employee.khmerLastName].filter(Boolean).join(' ')) }}</dd></div><div><dt>English Name</dt><dd>{{ value([employee.englishFirstName,employee.englishLastName].filter(Boolean).join(' ')) }}</dd></div><div><dt>Gender</dt><dd>{{ value(employee.gender) }}</dd></div><div><dt>Date of Birth</dt><dd>{{ value(employee.dateOfBirth) }}</dd></div><div><dt>Nationality</dt><dd>{{ value(employee.nationality) }}</dd></div><div><dt>Marital Status</dt><dd>{{ value(employee.maritalStatus) }}</dd></div></dl></section>
    <section><h3>Contact & Personal</h3><dl><div><dt>Phone</dt><dd>{{ value(employee.phoneNumber) }}</dd></div><div><dt>Email</dt><dd>{{ value(employee.email) }}</dd></div><div><dt>Agent Person</dt><dd>{{ value(employee.agentPerson) }}</dd></div><div><dt>Agent Phone</dt><dd>{{ value(employee.agentPhoneNumber) }}</dd></div><div><dt>Education</dt><dd>{{ value(employee.education) }}</dd></div><div><dt>Religion</dt><dd>{{ value(employee.religion) }}</dd></div></dl></section>
    <section><h3>Organization Assignment</h3><dl><div><dt>Company</dt><dd>{{ org(employee.company) }}</dd></div><div><dt>Branch</dt><dd>{{ org(employee.branch) }}</dd></div><div><dt>Department</dt><dd>{{ org(employee.department) }}</dd></div><div><dt>Position</dt><dd>{{ org(employee.position) }}</dd></div><div><dt>Line</dt><dd>{{ org(employee.line) }}</dd></div><div><dt>Shift</dt><dd>{{ org(employee.shift) }}</dd></div><div><dt>Employee Type</dt><dd>{{ org(employee.employeeType) }}</dd></div></dl></section>
    <section><h3>Employment</h3><dl><div><dt>Join Date</dt><dd>{{ value(employee.joinDate) }}</dd></div><div><dt>Resign Date</dt><dd>{{ value(employee.resignDate) }}</dd></div><div><dt>Resign Reason</dt><dd>{{ value(employee.resignReason) }}</dd></div><div><dt>Recruitment Channel</dt><dd>{{ org(employee.recruitmentChannel) }}</dd></div><div><dt>Record Status</dt><dd>{{ value(employee.recordStatus) }}</dd></div></dl></section>
    <section><h3>Addresses</h3><dl class="employee-details__single"><div><dt>Birth</dt><dd>{{ address(employee.birthAddress) }}</dd></div><div><dt>Permanent</dt><dd>{{ address(employee.permanentAddress) }}</dd></div></dl></section>
    <section><h3>Documents</h3><dl><div v-for="(item,key) in employee.documents" :key="key"><dt>{{ key }}</dt><dd>{{ value(item) }}</dd></div></dl></section>
    <section><h3>Machine Skills</h3><dl><div v-for="(item,key) in employee.machineSkills" :key="key"><dt>{{ key }}</dt><dd>{{ value(item) }}</dd></div></dl></section>
    <section><h3>Additional Information</h3><dl class="employee-details__single"><div><dt>Note</dt><dd>{{ value(employee.note) }}</dd></div><div><dt>Remark</dt><dd>{{ value(employee.remark) }}</dd></div><div><dt>Created</dt><dd>{{ value(employee.createdAt) }}</dd></div><div><dt>Updated</dt><dd>{{ value(employee.updatedAt) }}</dd></div></dl></section>
  </div>
</Drawer></template>
<style scoped>.employee-details-drawer{width:min(46rem,96vw)!important}.employee-details{display:grid;gap:1rem}.employee-details__loading{display:grid;min-height:20rem;place-items:center}.employee-details__profile{display:flex;align-items:center;gap:1rem}.employee-details__profile img{width:4rem;height:4rem;border-radius:50%;object-fit:cover}.employee-details__profile h2,.employee-details__profile p{margin:0 0 .25rem}.employee-details section{display:grid;gap:.65rem;padding:1rem;border:1px solid var(--p-content-border-color,#e2e8f0);border-radius:.65rem}.employee-details h3{margin:0;font-size:.85rem}.employee-details dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem 1rem;margin:0}.employee-details dl.employee-details__single{grid-template-columns:1fr}.employee-details dl div{min-width:0}.employee-details dt{color:var(--p-text-muted-color,#64748b);font-size:.68rem;font-weight:600;text-transform:capitalize}.employee-details dd{margin:.15rem 0 0;overflow-wrap:anywhere;font-size:.78rem}@media(max-width:560px){.employee-details dl{grid-template-columns:1fr}}</style>
